name: SonarCloud

on:
  push:
    branches: [main]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v7.1.0
        env:
            SONAR_TOKEN: 8c513d4da8819410b0293fd83eb95c7dbf219224
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=AdrijaDastidar_MPPI-GA
            -Dsonar.organization=adrijadastidar
            -Dsonar.host.url=https://sonarcloud.io
